[project]
name = "pac-man"
version = "0.1.0"
description = "Recreation of the arcade game Pac-Man"
readme = "README.md"
authors = [{ name = "ldreger" }, { name = "mimeyer" }]
requires-python = ">=3.13,<3.14"
dependencies = [
    "argparse>=1.4.0",
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "pygame>=2.6.1",
    "pylance>=11.0.0",
    "rich>=15.0.0",
    "mazegenerator",
    "logging>=0.4.9.6",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pac_man"
module-root = "src"
source-include = ["data/**"]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }
mlx = { path = "mlx-2.4-py3-none-any.whl" }

[tool.uv.workspace]
members = [
    "utils",
]

[project.scripts]
pac-man = "pac_man:main"
